- name: Set Hostname
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copy Expense Config file file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf


- name: Import common role - App Pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /usr/share/nginx/html
    app_user: root
    component: frontend

- name: Starting Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
    enabled: yes

- name: Import ELK -role filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Import Prometheus - Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter






