
- name: Generate Alert YAML File
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /tmp/{{component}}-{{env}}.yml

- name: Upload Alert File to S3
  ansible.builtin.shell: aws s3 cp /tmp/{{component}}-{{env}}.yml s3://bpk-prometheus-alerts/{{component}}-{{env}}.yml

- name: Trigger Prometheus Reload Job
  ansible.builtin.shell: curl -u {{ lookup('amazon.aws.aws_ssm', 'jenkins.username', region='us-east-1' ) }}:{{ lookup('amazon.aws.aws_ssm', 'jenkins.password', region='us-east-1' ) }}  "http://54.234.226.222:8080/job/prometheus-reload/build?token=prometheus"

    #JENKINS_URL/job/prometheus-reload/build?token=TOKEN_NAME
#  curl -u admin:admin123 "https://54.234.226.222:8080/job/prometheus-reload/build?token=prometheus"


