- name: Copy Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Copy Alert Rules
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /opt/prometheus/alert-rules.yml

- name: Starting prometheus Service
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded
    enabled: yes

- name: Copy Alert manager config
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Starting prometheus Service
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded
    enabled: yes