groups:
  - name: {{component}}-{{env}}
    rules:
      - alert: CPUUsageAlert
        expr: avg by (instance) (100 - (rate(node_cpu_seconds_total{mode="idle"}[5m]) * 100)) > 70
        for: 1m
        labels:
          severity: Warning
          component: {{component}}
          env: {{env}}
        annotations:
          summary: Warning | CPU Usage Alert
          description: "CPU usage is above 70% for the last 1 minute "

      - alert: CPUUsageAlert
        expr: avg by (instance) (100 - (rate(node_cpu_seconds_total{mode="idle"}[5m]) * 100)) > 90
        for: 1m
        labels:
          severity: Critical
          component: {{component}}
          env: {{env}}
        annotations:
          summary: Critical | CPU Usage Alert
          description: "CPU usage is above 90% for the last 1 minute "

      - alert: MemoryUsedAlert
        expr: ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes) * 100 > 70
        for: 1m
        labels:
          severity: Warning
          component: {{component}}
          env: {{env}}
        annotations:
          summary: Warning | Memory Used Alert
          description: "Memory Usage  is above 70% for the last 1 minute "

      - alert: MemoryUsedAlert
        expr: ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes) * 100 > 90
        for: 1m
        labels:
          severity: Critical
          component: {{component}}
          env: {{env}}
        annotations:
          summary: Critical| Memory Used Alert
          description: "Memory Usage  is above 90% for the last 1 minute "

      - alert: NetworkBWMonitorWaitQueue
        expr: rate(node_ethtool_bw_in_allowance_exceeded[1m]) > 0
        for: 3m
        labels:
            severity: critical
            component: { { component } }
            env: { { env } }
        annotations:
            summary: Critical | Network Wait Queue High
            description: "Network Wait Queue High form last 1 minute "

      - alert: NginxServiceMonitor
        expr: node_systemd_unit_state{exported_name="nginx.service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
          component: { { component } }
          env: { { env } }
        annotations:
          summary: Critical | Frontend Nginx Service Down
          description: " Frontend Nginx Service Down form last 1 minute "
          ##